export const DIRECTORIES_REQUESTING = 'DIRECTORIES_REQUESTING';
export const DIRECTORIES_RECEIVED = 'DIRECTORIES_RECEIVED';
export const DIRECTORIES_REQUEST_FAILED = 'DIRECTORIES_REQUEST_FAILED';

export const DIRECTORY_ADD_REQUESTING = 'DIRECTORY_ADD_REQUESTING';
export const DIRECTORY_ADD_COMPLETED = 'DIRECTORY_ADD_COMPLETED';
export const DIRECTORY_ADD_REQUEST_FAILED = 'DIRECTORY_ADD_REQUEST_FAILED';

export const DIRECTORY_UPDATE_REQUESTING = 'DIRECTORY_UPDATE_REQUESTING';
export const DIRECTORY_UPDATE_COMPLETED = 'DIRECTORY_UPDATE_COMPLETED';
export const DIRECTORY_UPDATE_REQUEST_FAILED = 'DIRECTORY_UPDATE_REQUEST_FAILED';

export const DIRECTORY_DELETE_REQUESTING = 'DIRECTORY_DELETE_REQUESTING';
export const DIRECTORY_DELETE_COMPLETED = 'DIRECTORY_DELETE_COMPLETED';
export const DIRECTORY_DELETE_REQUEST_FAILED = 'DIRECTORY_DELETE_REQUEST_FAILED';
