export const NOTICES_REQUESTING = 'NOTICES_REQUESTING';
export const NOTICES_RECEIVED = 'NOTICES_RECEIVED';
export const NOTICES_REQUEST_FAILED = 'NOTES_REQUEST_FAILED';

export const NOTICE_ADD_REQUESTING = 'NOTICE_ADD_REQUESTING';
export const NOTICE_ADD_RECEIVED = 'NOTICE_ADD_RECEIVED';
export const NOTICE_ADD_REQUEST_FAILED = 'NOTICE_ADD_REQUEST_FAILED';

export const NOTICE_UPDATE_REQUESTING = 'NOTICE_UPDATE_REQUESTING';
export const NOTICE_UPDATE_RECEIVED = 'NOTICE_UPDATE_RECEIVED';
export const NOTICE_UPDATE_REQUEST_FAILED = 'NOTICE_UPDATE_REQUEST_FAILED';

export const CHANGE_NOTICE_ITEMS_POSITION_REQUESTING = 'CHANGE_NOTICE_ITEMS_POSITION_REQUESTING';
export const CHANGE_NOTICE_ITEM_POSITION_RECEIVED = 'CHANGE_NOTICE_ITEM_POSITION_RECEIVED';
export const CHANGE_NOTICE_ITEM_POSITION_FAILED = 'CHANGE_NOTICE_ITEM_POSITION_FAILED';

export const NOTICE_DELETE_REQUESTING = 'NOTICE_DELETE_REQUESTING';
export const NOTICE_DELETE_RECEIVED = 'NOTICE_DELETE_RECEIVED';
export const NOTICE_DELETE_FAILED = 'NOTICE_DELETE_FAILED';
